version: '3'

networks:
  inside:
    driver: bridge
  outside:
    external:
      name: webproxy

volumes:
  dlbam-db:
    external:
      name: dlbam-db
  dlbam-backend-app:
    external:
      name: dlbam-backend-app
  dlbam-frontend-app:
    external:
      name: dlbam-frontend-app

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - dlbam-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_strapi
      MYSQL_USER: strapi_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inside

  backend:
    build: ./backend/
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - dlbam-backend-app:/var/lib/mysql
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: db_strapi
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_SSL: "false"
    networks:
      - inside

  frontend:
    build: ./frontend/
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - dlbam-frontend-app:/var/www/html
    environment:
      INTERNAL_API_URL: http://backend:1337
      EXTERNAL_API_URL: https://api.${DOMAIN}
    networks:
      - inside

  web:
    build: ./nginx/
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN},api.${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN},api.${DOMAIN}
    networks:
      - inside
      - outside
